site_name: ICTP-EAIFR HPC Guide
site_url: https://<your-repo>.readthedocs.io
repo_url: https://github.com/<your-username>/<your-repo>
repo_name: GitHub

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Cluster specifications: cluster_specifications.md
  - Remote login: remote_login.md
  - Linux command-line: linux_command_line.md
  - Text editor: text_editor.md
  - Software environments: software_environments.md
  - Job & Cluster Status: job_status.md
  - Serial Jobs: serial_jobs.md
  - Parallel Jobs: parallel_jobs.md
  - Data Transfer: data_transfer.md
  - More Info: more_info.md

